// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

public interface DAGJobJsonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.DAGJobJson)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string json = 1;</code>
   * @return The json.
   */
  java.lang.String getJson();
  /**
   * <code>string json = 1;</code>
   * @return The bytes for json.
   */
  com.google.protobuf.ByteString
      getJsonBytes();
}
