// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

public interface JobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.JobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * transformation of input
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * transformation of input
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * job's name
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * job's name
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * "Java", etc
   * </pre>
   *
   * <code>.rpc.LanguageType language = 3;</code>
   * @return The enum numeric value on the wire for language.
   */
  int getLanguageValue();
  /**
   * <pre>
   * "Java", etc
   * </pre>
   *
   * <code>.rpc.LanguageType language = 3;</code>
   * @return The language.
   */
  rpc.LanguageType getLanguage();

  /**
   * <pre>
   * "batch" or "stream"
   * </pre>
   *
   * <code>bool is_stream = 4;</code>
   * @return The isStream.
   */
  boolean getIsStream();

  /**
   * <pre>
   * "Local", "Cluster", "HRM"
   * </pre>
   *
   * <code>.rpc.PlatformType platform = 5;</code>
   * @return The enum numeric value on the wire for platform.
   */
  int getPlatformValue();
  /**
   * <pre>
   * "Local", "Cluster", "HRM"
   * </pre>
   *
   * <code>.rpc.PlatformType platform = 5;</code>
   * @return The platform.
   */
  rpc.PlatformType getPlatform();

  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  java.util.List<rpc.UBTable> 
      getInputListList();
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  rpc.UBTable getInputList(int index);
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  int getInputListCount();
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  java.util.List<? extends rpc.UBTableOrBuilder> 
      getInputListOrBuilderList();
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  rpc.UBTableOrBuilder getInputListOrBuilder(
      int index);

  /**
   * <pre>
   * Job's output unbounded table
   * </pre>
   *
   * <code>.rpc.UBTable output = 7;</code>
   * @return Whether the output field is set.
   */
  boolean hasOutput();
  /**
   * <pre>
   * Job's output unbounded table
   * </pre>
   *
   * <code>.rpc.UBTable output = 7;</code>
   * @return The output.
   */
  rpc.UBTable getOutput();
  /**
   * <pre>
   * Job's output unbounded table
   * </pre>
   *
   * <code>.rpc.UBTable output = 7;</code>
   */
  rpc.UBTableOrBuilder getOutputOrBuilder();
}
