// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

/**
 * Protobuf type {@code rpc.JobRequest}
 */
public final class JobRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.JobRequest)
    JobRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobRequest.newBuilder() to construct.
  private JobRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobRequest() {
    code_ = "";
    name_ = "";
    language_ = 0;
    platform_ = 0;
    inputList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            language_ = rawValue;
            break;
          }
          case 32: {

            isStream_ = input.readBool();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            platform_ = rawValue;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              inputList_ = new java.util.ArrayList<rpc.UBTable>();
              mutable_bitField0_ |= 0x00000001;
            }
            inputList_.add(
                input.readMessage(rpc.UBTable.parser(), extensionRegistry));
            break;
          }
          case 58: {
            rpc.UBTable.Builder subBuilder = null;
            if (output_ != null) {
              subBuilder = output_.toBuilder();
            }
            output_ = input.readMessage(rpc.UBTable.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(output_);
              output_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        inputList_ = java.util.Collections.unmodifiableList(inputList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rpc.SparkGProto.internal_static_rpc_JobRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rpc.SparkGProto.internal_static_rpc_JobRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rpc.JobRequest.class, rpc.JobRequest.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object code_;
  /**
   * <pre>
   * transformation of input
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * transformation of input
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * job's name
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * job's name
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_FIELD_NUMBER = 3;
  private int language_;
  /**
   * <pre>
   * "Java", etc
   * </pre>
   *
   * <code>.rpc.LanguageType language = 3;</code>
   * @return The enum numeric value on the wire for language.
   */
  @java.lang.Override public int getLanguageValue() {
    return language_;
  }
  /**
   * <pre>
   * "Java", etc
   * </pre>
   *
   * <code>.rpc.LanguageType language = 3;</code>
   * @return The language.
   */
  @java.lang.Override public rpc.LanguageType getLanguage() {
    @SuppressWarnings("deprecation")
    rpc.LanguageType result = rpc.LanguageType.valueOf(language_);
    return result == null ? rpc.LanguageType.UNRECOGNIZED : result;
  }

  public static final int IS_STREAM_FIELD_NUMBER = 4;
  private boolean isStream_;
  /**
   * <pre>
   * "batch" or "stream"
   * </pre>
   *
   * <code>bool is_stream = 4;</code>
   * @return The isStream.
   */
  @java.lang.Override
  public boolean getIsStream() {
    return isStream_;
  }

  public static final int PLATFORM_FIELD_NUMBER = 5;
  private int platform_;
  /**
   * <pre>
   * "Local", "Cluster", "HRM"
   * </pre>
   *
   * <code>.rpc.PlatformType platform = 5;</code>
   * @return The enum numeric value on the wire for platform.
   */
  @java.lang.Override public int getPlatformValue() {
    return platform_;
  }
  /**
   * <pre>
   * "Local", "Cluster", "HRM"
   * </pre>
   *
   * <code>.rpc.PlatformType platform = 5;</code>
   * @return The platform.
   */
  @java.lang.Override public rpc.PlatformType getPlatform() {
    @SuppressWarnings("deprecation")
    rpc.PlatformType result = rpc.PlatformType.valueOf(platform_);
    return result == null ? rpc.PlatformType.UNRECOGNIZED : result;
  }

  public static final int INPUT_LIST_FIELD_NUMBER = 6;
  private java.util.List<rpc.UBTable> inputList_;
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  @java.lang.Override
  public java.util.List<rpc.UBTable> getInputListList() {
    return inputList_;
  }
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends rpc.UBTableOrBuilder> 
      getInputListOrBuilderList() {
    return inputList_;
  }
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  @java.lang.Override
  public int getInputListCount() {
    return inputList_.size();
  }
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  @java.lang.Override
  public rpc.UBTable getInputList(int index) {
    return inputList_.get(index);
  }
  /**
   * <pre>
   * Job's input unbounded table list
   * </pre>
   *
   * <code>repeated .rpc.UBTable input_list = 6;</code>
   */
  @java.lang.Override
  public rpc.UBTableOrBuilder getInputListOrBuilder(
      int index) {
    return inputList_.get(index);
  }

  public static final int OUTPUT_FIELD_NUMBER = 7;
  private rpc.UBTable output_;
  /**
   * <pre>
   * Job's output unbounded table
   * </pre>
   *
   * <code>.rpc.UBTable output = 7;</code>
   * @return Whether the output field is set.
   */
  @java.lang.Override
  public boolean hasOutput() {
    return output_ != null;
  }
  /**
   * <pre>
   * Job's output unbounded table
   * </pre>
   *
   * <code>.rpc.UBTable output = 7;</code>
   * @return The output.
   */
  @java.lang.Override
  public rpc.UBTable getOutput() {
    return output_ == null ? rpc.UBTable.getDefaultInstance() : output_;
  }
  /**
   * <pre>
   * Job's output unbounded table
   * </pre>
   *
   * <code>.rpc.UBTable output = 7;</code>
   */
  @java.lang.Override
  public rpc.UBTableOrBuilder getOutputOrBuilder() {
    return getOutput();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (language_ != rpc.LanguageType.Java.getNumber()) {
      output.writeEnum(3, language_);
    }
    if (isStream_ != false) {
      output.writeBool(4, isStream_);
    }
    if (platform_ != rpc.PlatformType.Local.getNumber()) {
      output.writeEnum(5, platform_);
    }
    for (int i = 0; i < inputList_.size(); i++) {
      output.writeMessage(6, inputList_.get(i));
    }
    if (output_ != null) {
      output.writeMessage(7, getOutput());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (language_ != rpc.LanguageType.Java.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, language_);
    }
    if (isStream_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isStream_);
    }
    if (platform_ != rpc.PlatformType.Local.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, platform_);
    }
    for (int i = 0; i < inputList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, inputList_.get(i));
    }
    if (output_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getOutput());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rpc.JobRequest)) {
      return super.equals(obj);
    }
    rpc.JobRequest other = (rpc.JobRequest) obj;

    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (language_ != other.language_) return false;
    if (getIsStream()
        != other.getIsStream()) return false;
    if (platform_ != other.platform_) return false;
    if (!getInputListList()
        .equals(other.getInputListList())) return false;
    if (hasOutput() != other.hasOutput()) return false;
    if (hasOutput()) {
      if (!getOutput()
          .equals(other.getOutput())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + language_;
    hash = (37 * hash) + IS_STREAM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsStream());
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    if (getInputListCount() > 0) {
      hash = (37 * hash) + INPUT_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getInputListList().hashCode();
    }
    if (hasOutput()) {
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rpc.JobRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rpc.JobRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rpc.JobRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rpc.JobRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rpc.JobRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rpc.JobRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rpc.JobRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rpc.JobRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rpc.JobRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rpc.JobRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rpc.JobRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rpc.JobRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rpc.JobRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.JobRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.JobRequest)
      rpc.JobRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.SparkGProto.internal_static_rpc_JobRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.SparkGProto.internal_static_rpc_JobRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rpc.JobRequest.class, rpc.JobRequest.Builder.class);
    }

    // Construct using rpc.JobRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInputListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = "";

      name_ = "";

      language_ = 0;

      isStream_ = false;

      platform_ = 0;

      if (inputListBuilder_ == null) {
        inputList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        inputListBuilder_.clear();
      }
      if (outputBuilder_ == null) {
        output_ = null;
      } else {
        output_ = null;
        outputBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rpc.SparkGProto.internal_static_rpc_JobRequest_descriptor;
    }

    @java.lang.Override
    public rpc.JobRequest getDefaultInstanceForType() {
      return rpc.JobRequest.getDefaultInstance();
    }

    @java.lang.Override
    public rpc.JobRequest build() {
      rpc.JobRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rpc.JobRequest buildPartial() {
      rpc.JobRequest result = new rpc.JobRequest(this);
      int from_bitField0_ = bitField0_;
      result.code_ = code_;
      result.name_ = name_;
      result.language_ = language_;
      result.isStream_ = isStream_;
      result.platform_ = platform_;
      if (inputListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          inputList_ = java.util.Collections.unmodifiableList(inputList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.inputList_ = inputList_;
      } else {
        result.inputList_ = inputListBuilder_.build();
      }
      if (outputBuilder_ == null) {
        result.output_ = output_;
      } else {
        result.output_ = outputBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rpc.JobRequest) {
        return mergeFrom((rpc.JobRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rpc.JobRequest other) {
      if (other == rpc.JobRequest.getDefaultInstance()) return this;
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.language_ != 0) {
        setLanguageValue(other.getLanguageValue());
      }
      if (other.getIsStream() != false) {
        setIsStream(other.getIsStream());
      }
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (inputListBuilder_ == null) {
        if (!other.inputList_.isEmpty()) {
          if (inputList_.isEmpty()) {
            inputList_ = other.inputList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInputListIsMutable();
            inputList_.addAll(other.inputList_);
          }
          onChanged();
        }
      } else {
        if (!other.inputList_.isEmpty()) {
          if (inputListBuilder_.isEmpty()) {
            inputListBuilder_.dispose();
            inputListBuilder_ = null;
            inputList_ = other.inputList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            inputListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInputListFieldBuilder() : null;
          } else {
            inputListBuilder_.addAllMessages(other.inputList_);
          }
        }
      }
      if (other.hasOutput()) {
        mergeOutput(other.getOutput());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      rpc.JobRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (rpc.JobRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * transformation of input
     * </pre>
     *
     * <code>string code = 1;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * transformation of input
     * </pre>
     *
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * transformation of input
     * </pre>
     *
     * <code>string code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * transformation of input
     * </pre>
     *
     * <code>string code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * transformation of input
     * </pre>
     *
     * <code>string code = 1;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * job's name
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * job's name
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * job's name
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * job's name
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * job's name
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int language_ = 0;
    /**
     * <pre>
     * "Java", etc
     * </pre>
     *
     * <code>.rpc.LanguageType language = 3;</code>
     * @return The enum numeric value on the wire for language.
     */
    @java.lang.Override public int getLanguageValue() {
      return language_;
    }
    /**
     * <pre>
     * "Java", etc
     * </pre>
     *
     * <code>.rpc.LanguageType language = 3;</code>
     * @param value The enum numeric value on the wire for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageValue(int value) {
      
      language_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "Java", etc
     * </pre>
     *
     * <code>.rpc.LanguageType language = 3;</code>
     * @return The language.
     */
    @java.lang.Override
    public rpc.LanguageType getLanguage() {
      @SuppressWarnings("deprecation")
      rpc.LanguageType result = rpc.LanguageType.valueOf(language_);
      return result == null ? rpc.LanguageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * "Java", etc
     * </pre>
     *
     * <code>.rpc.LanguageType language = 3;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(rpc.LanguageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      language_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "Java", etc
     * </pre>
     *
     * <code>.rpc.LanguageType language = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      
      language_ = 0;
      onChanged();
      return this;
    }

    private boolean isStream_ ;
    /**
     * <pre>
     * "batch" or "stream"
     * </pre>
     *
     * <code>bool is_stream = 4;</code>
     * @return The isStream.
     */
    @java.lang.Override
    public boolean getIsStream() {
      return isStream_;
    }
    /**
     * <pre>
     * "batch" or "stream"
     * </pre>
     *
     * <code>bool is_stream = 4;</code>
     * @param value The isStream to set.
     * @return This builder for chaining.
     */
    public Builder setIsStream(boolean value) {
      
      isStream_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "batch" or "stream"
     * </pre>
     *
     * <code>bool is_stream = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsStream() {
      
      isStream_ = false;
      onChanged();
      return this;
    }

    private int platform_ = 0;
    /**
     * <pre>
     * "Local", "Cluster", "HRM"
     * </pre>
     *
     * <code>.rpc.PlatformType platform = 5;</code>
     * @return The enum numeric value on the wire for platform.
     */
    @java.lang.Override public int getPlatformValue() {
      return platform_;
    }
    /**
     * <pre>
     * "Local", "Cluster", "HRM"
     * </pre>
     *
     * <code>.rpc.PlatformType platform = 5;</code>
     * @param value The enum numeric value on the wire for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformValue(int value) {
      
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "Local", "Cluster", "HRM"
     * </pre>
     *
     * <code>.rpc.PlatformType platform = 5;</code>
     * @return The platform.
     */
    @java.lang.Override
    public rpc.PlatformType getPlatform() {
      @SuppressWarnings("deprecation")
      rpc.PlatformType result = rpc.PlatformType.valueOf(platform_);
      return result == null ? rpc.PlatformType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * "Local", "Cluster", "HRM"
     * </pre>
     *
     * <code>.rpc.PlatformType platform = 5;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(rpc.PlatformType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "Local", "Cluster", "HRM"
     * </pre>
     *
     * <code>.rpc.PlatformType platform = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      
      platform_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<rpc.UBTable> inputList_ =
      java.util.Collections.emptyList();
    private void ensureInputListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        inputList_ = new java.util.ArrayList<rpc.UBTable>(inputList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        rpc.UBTable, rpc.UBTable.Builder, rpc.UBTableOrBuilder> inputListBuilder_;

    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public java.util.List<rpc.UBTable> getInputListList() {
      if (inputListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(inputList_);
      } else {
        return inputListBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public int getInputListCount() {
      if (inputListBuilder_ == null) {
        return inputList_.size();
      } else {
        return inputListBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public rpc.UBTable getInputList(int index) {
      if (inputListBuilder_ == null) {
        return inputList_.get(index);
      } else {
        return inputListBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder setInputList(
        int index, rpc.UBTable value) {
      if (inputListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputListIsMutable();
        inputList_.set(index, value);
        onChanged();
      } else {
        inputListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder setInputList(
        int index, rpc.UBTable.Builder builderForValue) {
      if (inputListBuilder_ == null) {
        ensureInputListIsMutable();
        inputList_.set(index, builderForValue.build());
        onChanged();
      } else {
        inputListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder addInputList(rpc.UBTable value) {
      if (inputListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputListIsMutable();
        inputList_.add(value);
        onChanged();
      } else {
        inputListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder addInputList(
        int index, rpc.UBTable value) {
      if (inputListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputListIsMutable();
        inputList_.add(index, value);
        onChanged();
      } else {
        inputListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder addInputList(
        rpc.UBTable.Builder builderForValue) {
      if (inputListBuilder_ == null) {
        ensureInputListIsMutable();
        inputList_.add(builderForValue.build());
        onChanged();
      } else {
        inputListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder addInputList(
        int index, rpc.UBTable.Builder builderForValue) {
      if (inputListBuilder_ == null) {
        ensureInputListIsMutable();
        inputList_.add(index, builderForValue.build());
        onChanged();
      } else {
        inputListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder addAllInputList(
        java.lang.Iterable<? extends rpc.UBTable> values) {
      if (inputListBuilder_ == null) {
        ensureInputListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inputList_);
        onChanged();
      } else {
        inputListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder clearInputList() {
      if (inputListBuilder_ == null) {
        inputList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        inputListBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public Builder removeInputList(int index) {
      if (inputListBuilder_ == null) {
        ensureInputListIsMutable();
        inputList_.remove(index);
        onChanged();
      } else {
        inputListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public rpc.UBTable.Builder getInputListBuilder(
        int index) {
      return getInputListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public rpc.UBTableOrBuilder getInputListOrBuilder(
        int index) {
      if (inputListBuilder_ == null) {
        return inputList_.get(index);  } else {
        return inputListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public java.util.List<? extends rpc.UBTableOrBuilder> 
         getInputListOrBuilderList() {
      if (inputListBuilder_ != null) {
        return inputListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(inputList_);
      }
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public rpc.UBTable.Builder addInputListBuilder() {
      return getInputListFieldBuilder().addBuilder(
          rpc.UBTable.getDefaultInstance());
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public rpc.UBTable.Builder addInputListBuilder(
        int index) {
      return getInputListFieldBuilder().addBuilder(
          index, rpc.UBTable.getDefaultInstance());
    }
    /**
     * <pre>
     * Job's input unbounded table list
     * </pre>
     *
     * <code>repeated .rpc.UBTable input_list = 6;</code>
     */
    public java.util.List<rpc.UBTable.Builder> 
         getInputListBuilderList() {
      return getInputListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        rpc.UBTable, rpc.UBTable.Builder, rpc.UBTableOrBuilder> 
        getInputListFieldBuilder() {
      if (inputListBuilder_ == null) {
        inputListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            rpc.UBTable, rpc.UBTable.Builder, rpc.UBTableOrBuilder>(
                inputList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        inputList_ = null;
      }
      return inputListBuilder_;
    }

    private rpc.UBTable output_;
    private com.google.protobuf.SingleFieldBuilderV3<
        rpc.UBTable, rpc.UBTable.Builder, rpc.UBTableOrBuilder> outputBuilder_;
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     * @return Whether the output field is set.
     */
    public boolean hasOutput() {
      return outputBuilder_ != null || output_ != null;
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     * @return The output.
     */
    public rpc.UBTable getOutput() {
      if (outputBuilder_ == null) {
        return output_ == null ? rpc.UBTable.getDefaultInstance() : output_;
      } else {
        return outputBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    public Builder setOutput(rpc.UBTable value) {
      if (outputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        output_ = value;
        onChanged();
      } else {
        outputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    public Builder setOutput(
        rpc.UBTable.Builder builderForValue) {
      if (outputBuilder_ == null) {
        output_ = builderForValue.build();
        onChanged();
      } else {
        outputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    public Builder mergeOutput(rpc.UBTable value) {
      if (outputBuilder_ == null) {
        if (output_ != null) {
          output_ =
            rpc.UBTable.newBuilder(output_).mergeFrom(value).buildPartial();
        } else {
          output_ = value;
        }
        onChanged();
      } else {
        outputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    public Builder clearOutput() {
      if (outputBuilder_ == null) {
        output_ = null;
        onChanged();
      } else {
        output_ = null;
        outputBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    public rpc.UBTable.Builder getOutputBuilder() {
      
      onChanged();
      return getOutputFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    public rpc.UBTableOrBuilder getOutputOrBuilder() {
      if (outputBuilder_ != null) {
        return outputBuilder_.getMessageOrBuilder();
      } else {
        return output_ == null ?
            rpc.UBTable.getDefaultInstance() : output_;
      }
    }
    /**
     * <pre>
     * Job's output unbounded table
     * </pre>
     *
     * <code>.rpc.UBTable output = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        rpc.UBTable, rpc.UBTable.Builder, rpc.UBTableOrBuilder> 
        getOutputFieldBuilder() {
      if (outputBuilder_ == null) {
        outputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            rpc.UBTable, rpc.UBTable.Builder, rpc.UBTableOrBuilder>(
                getOutput(),
                getParentForChildren(),
                isClean());
        output_ = null;
      }
      return outputBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.JobRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.JobRequest)
  private static final rpc.JobRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rpc.JobRequest();
  }

  public static rpc.JobRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobRequest>
      PARSER = new com.google.protobuf.AbstractParser<JobRequest>() {
    @java.lang.Override
    public JobRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rpc.JobRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

