// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

public interface JobReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.JobReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string compile_info = 1;</code>
   * @return The compileInfo.
   */
  java.lang.String getCompileInfo();
  /**
   * <code>string compile_info = 1;</code>
   * @return The bytes for compileInfo.
   */
  com.google.protobuf.ByteString
      getCompileInfoBytes();

  /**
   * <code>string compile_err_info = 2;</code>
   * @return The compileErrInfo.
   */
  java.lang.String getCompileErrInfo();
  /**
   * <code>string compile_err_info = 2;</code>
   * @return The bytes for compileErrInfo.
   */
  com.google.protobuf.ByteString
      getCompileErrInfoBytes();

  /**
   * <code>string run_info = 3;</code>
   * @return The runInfo.
   */
  java.lang.String getRunInfo();
  /**
   * <code>string run_info = 3;</code>
   * @return The bytes for runInfo.
   */
  com.google.protobuf.ByteString
      getRunInfoBytes();

  /**
   * <code>string run_err_info = 4;</code>
   * @return The runErrInfo.
   */
  java.lang.String getRunErrInfo();
  /**
   * <code>string run_err_info = 4;</code>
   * @return The bytes for runErrInfo.
   */
  com.google.protobuf.ByteString
      getRunErrInfoBytes();
}
