// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

/**
 * Protobuf enum {@code rpc.LanguageType}
 */
public enum LanguageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * recommended
   * </pre>
   *
   * <code>Java = 0;</code>
   */
  Java(0),
  /**
   * <code>Scala = 1;</code>
   */
  Scala(1),
  /**
   * <code>Python = 2;</code>
   */
  Python(2),
  /**
   * <code>SQL = 3;</code>
   */
  SQL(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * recommended
   * </pre>
   *
   * <code>Java = 0;</code>
   */
  public static final int Java_VALUE = 0;
  /**
   * <code>Scala = 1;</code>
   */
  public static final int Scala_VALUE = 1;
  /**
   * <code>Python = 2;</code>
   */
  public static final int Python_VALUE = 2;
  /**
   * <code>SQL = 3;</code>
   */
  public static final int SQL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LanguageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LanguageType forNumber(int value) {
    switch (value) {
      case 0: return Java;
      case 1: return Scala;
      case 2: return Python;
      case 3: return SQL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LanguageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LanguageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LanguageType>() {
          public LanguageType findValueByNumber(int number) {
            return LanguageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return rpc.SparkGProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final LanguageType[] VALUES = values();

  public static LanguageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LanguageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:rpc.LanguageType)
}

