// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

/**
 * Protobuf enum {@code rpc.TableType}
 */
public enum TableType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>File = 0;</code>
   */
  File(0),
  /**
   * <code>Kafka = 1;</code>
   */
  Kafka(1),
  /**
   * <code>Console = 2;</code>
   */
  Console(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>File = 0;</code>
   */
  public static final int File_VALUE = 0;
  /**
   * <code>Kafka = 1;</code>
   */
  public static final int Kafka_VALUE = 1;
  /**
   * <code>Console = 2;</code>
   */
  public static final int Console_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TableType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TableType forNumber(int value) {
    switch (value) {
      case 0: return File;
      case 1: return Kafka;
      case 2: return Console;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TableType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TableType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TableType>() {
          public TableType findValueByNumber(int number) {
            return TableType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return rpc.SparkGProto.getDescriptor().getEnumTypes().get(5);
  }

  private static final TableType[] VALUES = values();

  public static TableType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TableType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:rpc.TableType)
}

