// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package rpc;

public interface UBTableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.UBTable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * table's name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * table's name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * File or Kafka or Console
   * </pre>
   *
   * <code>.rpc.TableType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * File or Kafka or Console
   * </pre>
   *
   * <code>.rpc.TableType type = 2;</code>
   * @return The type.
   */
  rpc.TableType getType();

  /**
   * <pre>
   * Kafka's URL
   * </pre>
   *
   * <code>string URL = 3;</code>
   * @return The uRL.
   */
  java.lang.String getURL();
  /**
   * <pre>
   * Kafka's URL
   * </pre>
   *
   * <code>string URL = 3;</code>
   * @return The bytes for uRL.
   */
  com.google.protobuf.ByteString
      getURLBytes();

  /**
   * <pre>
   * File's path
   * </pre>
   *
   * <code>string path = 4;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <pre>
   * File's path
   * </pre>
   *
   * <code>string path = 4;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * Fafka's topic
   * </pre>
   *
   * <code>string topic = 5;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * Fafka's topic
   * </pre>
   *
   * <code>string topic = 5;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * tables's schema, e.g.,  "id IntegerType, time LongType, img StringType"
   * </pre>
   *
   * <code>string schema = 6;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <pre>
   * tables's schema, e.g.,  "id IntegerType, time LongType, img StringType"
   * </pre>
   *
   * <code>string schema = 6;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();

  /**
   * <code>bool use_checkpoint = 7;</code>
   * @return The useCheckpoint.
   */
  boolean getUseCheckpoint();
}
